### ISSUE TITLE
Support for MariaDB

### ISSUE THREAD

**Issue by halles** [linode/longview#20]
Since CentOS 7, mysql has been replaced by MariaDB. I supposed it would be no issue at all, but it seems the necessary modules are not installed since mysql is never actually installed. Is there a workaround? Is support assigned on a milestone already?

**Comment by levlaz** [comment]
Hello @halles, I apologize for the delay in response. Thank you for this issue. 

Since MariaDB is a drop in replacement for MySQL, it is supported in Longview by default. In order to get it to work, you will need to do a little bit of manual configuration as described in this guide: https://www.linode.com/docs/platform/longview/longview-app-for-mysql/ 

I spun up a brand new Linode with CentOS 7, installed mariadb-server and verified that following the guide allowed me to view data about MariaDB in Longview. The specific steps that I took are: 

1. Open up MariaDB by typing in `mysql`Created a linode-longview user in MariaDB

```sql
CREATE USER 'linode-longview'@'localhost' IDENTIFIED BY 'YOUR_PASSWORD';
flush privileges;
```
